#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
        typeit=1
        shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
        dmenu=dmenu-wl
        xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
        dmenu=dmenu
        xdotool="xdotool type --clearmodifiers --file -"
else
        echo "Error: No Wayland or X11 display detected" >&2
        exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")

pw() {
	clipctl disable
	pass "$1" | grep "login:" | sed 's/login: //g' | xclip -r -selection clipboard && notify-send "passmenu" "login copied"
	sleep 5
	pass -c "$1" 2>/dev/null && notify-send "passmenu" "password copied"
	sleep 5
	pass otp -c "$1" 2>/dev/null && notify-send "passmenu" "otp copied"
	clipctl enable
}


[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pw "$password"
        #pass show -c "$password" 2>/dev/null
else
        pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
